### ISSUE TITLE
auth: move system_auth under RAFT - follow-ups (epic)

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylla#18867]
A continuation of https://github.com/scylladb/scylladb/issues/16970 with issues that are not that crucial and hence didn't make it into 6.0.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-enterprise/issues/3764
- [ ] https://github.com/scylladb/scylladb/issues/9862
- [ ] https://github.com/scylladb/scylladb/issues/17738
- [ ] https://github.com/scylladb/scylladb/issues/18931
```

**Comment by Michal-Leszczynski** [comment]
I observed that creating a fresh cluster with Scylla 6.0 results in creating an empty `system_auth` keyspace.
Tables that previously belonged to it (e.g. `system_auth.roles`), are correctly created under the `system` keyspace. 

@ptrsmrn Is this expected that the empty `system_auth` keyspace is created, or was it unintentionally left there?

**Comment by nuivall** [comment]
It's deliberately done like this as cqlsh has a weird dependency on it.

**Comment by mykaul** [comment]
> It's deliberately done like this as cqlsh has a weird dependency on it.

I couldn't find a bug. Does it imply it doesn't support authv2? For example, how would https://github.com/scylladb/scylla-cqlsh/blob/73bdbeb03648efe857b54c5e7459b5e71cd69fd4/bin/cqlsh.py#L1128 work?

**Comment by nuivall** [comment]
There is no bug as it was prevented before it occurred by leaving the keyspace intact, work was done here: https://github.com/scylladb/scylladb/pull/17939

**Comment by mykaul** [comment]
@ptrsmrn , @nuivall  - what's critical to continue and work on here, and what can be deferred to future versions?

**Comment by ptrsmrn** [comment]
I'm guessing it'd be could to finalize these:
- [ ] https://github.com/scylladb/scylladb/issues/17740
- [ ] https://github.com/scylladb/scylladb/issues/17904
- [ ] https://github.com/scylladb/scylladb/issues/19153

While the rest can probably be deferred.
