### ISSUE TITLE
Lightweight transactions: initial series follow up

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5202]
## 4.0

- [x] https://github.com/scylladb/scylla/issues/5644 regressions in commitlog-sync and bounce-to-shard patches
- [x] https://github.com/scylladb/scylla/issues/5682 writes to local.paxos create small sstables and cause a lot of compaction activity
- [x] https://github.com/scylladb/scylla/issues/5710 NULL value handling in IN list
- [x] https://github.com/scylladb/scylla/issues/5810 verify conditional batch size
- [x] https://github.com/scylladb/scylla/issues/5791 NULL handling in container values
- [x] https://github.com/scylladb/scylla/issues/5782 lwt: bind markers not working properly in LWT queries for float, double, uuid types with "(null)" bound value
- [x] https://github.com/scylladb/scylla/issues/5700 statement tracing crashes when used with lwt
- [x] log CQL queries in query_processor to be able to debug LWT performance
- [x] https://github.com/scylladb/scylla/issues/5792 add a test case for USING TTL, add a test case for INSERT JSON '{}'
- [x] https://github.com/scylladb/scylla/issues/5251 CAS consistency may be violated after a topology change
- [x] use "double quorum" pattern when joining node is included in get_paxos_endpoints(), rather than rely on "required_endpoints" number
- [x] verify that SET CONSISTENCY client-side  statement works
- [x] https://github.com/scylladb/scylla/issues/5775 add feature bit for LWT, refuse to perform an LWT across replicas in a heterogeneous (different veresion) setup. 
- [x]  https://github.com/scylladb/scylla/issues/5777 support LIKE operator in column conditions

### QA 
- [x] add tests for  CDC and LWT
- [x] move yacht tests to dtest/test.py
- [x] convert java unit tests to CQL format
- [x] add distributed tests according to the test plan
### Performance optimization
- [x] https://github.com/scylladb/scylla/issues/5771 optimize get_truncated_at() to avoid a full blown query on each learn 
- [x] switch to the right CPU on coordinator, to make sure there is the smallest amount of invoke_on() possible
- [x] make sure paxos table is sharded by partition key so that querying it doesn't involve invoke_on()
- [x] Randomize sleep/retry interval in ::cas()
- [x] verify Go driver is lwt-shard-aware (but only with protocolVersion=4)
- [x] verify Java driver is lwt-shard-aware (but only with cassandra protocolVersion=4)
- [x] https://github.com/scylladb/scylla/issues/5779 proactively prune records from system.paxos table to reduce Wamp during compaction

### Review follow-up
- [x] rewrite column_mask to be fixed size, use name column_set instead, consider adding std::begin/std::end
- [x] Add timeouts to system keyspace execute_cql(), so that saving / loading paxos state is interruptible
- [x] Refactor storage_proxy::mutate_internal() to avoid is_cas() dispatch in send_to_live_endpoints()\

**Comment by dorlaor** [comment]
It's needs an update since there is no 3.4 and we go directly to 4.0

**Comment by slivne** [comment]
@kostja please close the issue with 4.0 items create a new generic issue to track LWT for 4.1 and onwards

**Comment by longquanzheng** [comment]
Hi team, does ScyllaDB support batch of LWTs in a single shard of a table like Cassandra?

**Comment by gleb-cloudius** [comment]
If you mean batch statement for the same partition key then yes.
