### ISSUE TITLE
LWT follow up: 4.x

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6207]
## 4.x
- [ ] ensure jepsen tests work and contribute them to the upstream
- [ ] https://github.com/scylladb/scylla/issues/5252 Writes concurrent with a topology change may experience reduced effective CL
- [ ] LWT performance  (ops/sec) vary too much https://github.com/scylladb/scylla/issues/5834
- [ ] https://github.com/scylladb/scylla/issues/6068 - follow up related to iotune changes/cost model
- [ ] consider having a Cassandra compatibility flag for result set format
- [ ] Better error messages, as per https://issues.apache.org/jira/browse/CASSANDRA-15350
- [ ] https://github.com/scylladb/scylla/issues/5776 support UDT in column conditions
- [ ] https://github.com/scylladb/scylla/issues/5798 support expressions in column conditions
- [ ] https://github.com/scylladb/scylla/issues/6114 Do not sync commit log for non-essential Paxos

**Comment by longquanzheng** [comment]
Hi team, does ScyllaDB support batch of LWTs in a single shard of a table like Cassandra?

**Comment by kostja** [comment]
@longquanzheng the bugs database is not the right place to make a support request. Please refer to Scylla documentation at https://docs.scylladb.com/using-scylla/lwt/ or join Scylla Users Slack and ask for help there: http://slack.scylladb.com/

**Comment by slivne** [comment]
pushing this out we started working n RAFT - we will implement parts on need basis

**Comment by kostja** [comment]
@emdroid this is mistakenly a p1, it's an old follow up ticket from 3.x. As such you could close the ticket, since we're no longer tracking the remaining issues as a saga.
